# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-15 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
