# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=100)),
                ('status', models.CharField(default='AVAIL', max_length=100)),
            ],
        ),
    ]
