# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='status',
        ),
        migrations.AddField(
            model_name='times',
            name='is_avail',
            field=models.BooleanField(default=True),
        ),
    ]
