# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20181229_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='is_avail',
        ),
    ]
