# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_times_is_avail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_avail', models.BooleanField(default=True)),
                ('rest_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Restaurants', to='order.Restaurants')),
                ('slot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Time', to='order.Times')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('table_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restauranttimings',
            name='table_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='order.Tables'),
        ),
    ]
