# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181229_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttimings',
            old_name='rest_id',
            new_name='rest',
        ),
        migrations.RenameField(
            model_name='restauranttimings',
            old_name='slot_id',
            new_name='slot',
        ),
    ]
