# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20181229_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttimings',
            name='table_details',
        ),
        migrations.AddField(
            model_name='restauranttimings',
            name='table_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restauranttimings',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
