# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
