# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-09 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190108_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
