# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='contact',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
